# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'myproject-conn'
    subscriptionId: 'df6c7490-c44a-41e2-acda-b7c640bb976b'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'myproject-rg'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName myproject -linkedTemplateUri https://raw.githubusercontent.com/jleroux751/myproject-repo/main/CreateWebApp/linkedStorageAccount.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'